# Generated by Django 4.2.2 on 2023-06-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('periodo_ingresso', models.CharField(max_length=10)),
                ('nota_web_avancado', models.DecimalField(decimal_places=1, max_digits=3)),
                ('situacao', models.CharField(max_length=50)),
            ],
        ),
    ]
